exports.defaultHtmlHeadInjectDataKeys = [
  "APP_ROOT",
  "BASE_APPS_ENV_URL",
  "BASE_LAUNCH_ENV_URL",
  "BASE_SERVICE_ENV_URL",
  "BASE_WWW_ENV_URL",
  "CORE_APPS_ENV_URL",
  "CORE_ENV_URL",
  "CORE_SERVICE_ENV_URL",
  "NEW_RELIC_BROWSER_ID",
  "NEW_RELIC_BROWSER_KEY",
  "PRODUCT_APPS_ENV_URL",
  "PRODUCT_ENV_URL",
  "PRODUCT_SERVICE_ENV_URL"
];
